// <auto-generated />
namespace Tawh.NoTrace.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitData));
        
        string IMigrationMetadata.Id
        {
            get { return "201607190848416_InitData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
